plugins {
    id("bisq.java-library")
    id("bisq.protobuf")
}

dependencies {
    implementation("bisq:persistence:$version")
    implementation("bisq:java-se:$version")
    implementation("bisq:i18n:$version")
    implementation("bisq:security:$version")
    implementation("bisq:identity:$version")
    implementation("bisq:account:$version")
    implementation("bisq:offer:$version")
    implementation("bisq:contract:$version")
    implementation("bisq:trade:$version")
    implementation("bisq:bonded-roles:$version")
    implementation("bisq:settings:$version")
    implementation("bisq:burningman:$version")
    implementation("bisq:mu-sig:$version")
    implementation("bisq:user:$version")
    implementation("bisq:chat:$version")
    implementation("bisq:support:$version")
    implementation("bisq:presentation:$version")
    implementation("bisq:notifications:$version")
    implementation("bisq:bisq-easy:$version")
    implementation("bisq:application:$version")
    implementation("bisq:evolution:$version")
    implementation("bisq:os-specific:$version")
    implementation("bisq:wallet:$version")

    implementation("network:network:$version")
    implementation("network:network-identity:$version")

    implementation(libs.typesafe.config)
    implementation(libs.bundles.i2p)
    implementation(libs.bundles.rest.api.libs)
    implementation(libs.bundles.websocket.libs)
    implementation(libs.bouncycastle)
    implementation(libs.bouncycastle.pkix)
    implementation(libs.zxing.core)
}
